language: cpp
compiler:
    - clang
    - gcc
    - gcc-7
    - gcc-8

os:
    - linux
    - osx

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
    - autoconf-archive
    - gcc-7
    - gcc-8
    - libc++-dev
    - libc++abi-dev
  homebrew:
    packages:
    - gettext

matrix:
  exclude:
  - compiler: gcc-7
    os: osx
  - compiler: gcc-8
    os: osx

before_script:
    - ./.travis/bootstrap.sh

script:
    # Workaround Travis' clang not finding its headers.
    - if [[ $TRAVIS_OS_NAME == 'linux' && $CXX == 'clang++' ]]; then export CXX='clang++ -stdlib=libc++'; fi
    - ./configure
    - make
    - make check
    - ./test2_libxls test/files/test2.xls
